# config file for circleci
version: 2 
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: j256-simplelogging-{{ checksum "pom.xml" }}
      - run:
          name: Get maven project dependencies
          command: mvn -U dependency:go-offline compile
      # save the project dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: j256-simplelogging-{{ checksum "pom.xml" }}
      - run:
          name: mvn package
          command: mvn package
      # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard. 
      - store_test_results: 
          path: target/surefire-reports
      - run:
          name: Generate coverage report using jacoco
          command: mvn jacoco:report
      - run:
          name: Upload coverage report to CodeCov
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: Upload check
          command: bash x.sh
          when: always
      - run:
          name: Save test results
          when: always
          command: |
             mkdir -p ~/test-results/junit/
             find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit         

